name: interview

services:
  interview:
    container_name: interview-web
    image: interview:latest
    build:
      context: .
      # dockerfile: ./Dockerfiles/Dockerfile-dev
      dockerfile: ./Dockerfiles/Dockerfile-pro
    restart: unless-stopped
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    ports:
      - 3000:3000
