version: '3.4'

services:
  interview:
    image: interview
    build:
      context: interview
      dockerfile: ./Dockerfile
    container_name: interview
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
