version: '3.4'

services:
  interview:
    # 替换为真实的生产环境镜像和tag
    image: interview
    container_name: interview-web
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
